// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/deals.proto

package deals

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContactId     string                 `protobuf:"bytes,1,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Stage         string                 `protobuf:"bytes,4,opt,name=stage,proto3" json:"stage,omitempty"` // ejemplo: "open", "won", "lost"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDealRequest) Reset() {
	*x = CreateDealRequest{}
	mi := &file_proto_deals_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDealRequest) ProtoMessage() {}

func (x *CreateDealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deals_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDealRequest.ProtoReflect.Descriptor instead.
func (*CreateDealRequest) Descriptor() ([]byte, []int) {
	return file_proto_deals_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDealRequest) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

func (x *CreateDealRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateDealRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateDealRequest) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

type GetDealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDealRequest) Reset() {
	*x = GetDealRequest{}
	mi := &file_proto_deals_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDealRequest) ProtoMessage() {}

func (x *GetDealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deals_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDealRequest.ProtoReflect.Descriptor instead.
func (*GetDealRequest) Descriptor() ([]byte, []int) {
	return file_proto_deals_proto_rawDescGZIP(), []int{1}
}

func (x *GetDealRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContactId     string                 `protobuf:"bytes,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Stage         string                 `protobuf:"bytes,5,opt,name=stage,proto3" json:"stage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DealResponse) Reset() {
	*x = DealResponse{}
	mi := &file_proto_deals_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealResponse) ProtoMessage() {}

func (x *DealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deals_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealResponse.ProtoReflect.Descriptor instead.
func (*DealResponse) Descriptor() ([]byte, []int) {
	return file_proto_deals_proto_rawDescGZIP(), []int{2}
}

func (x *DealResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DealResponse) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

func (x *DealResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DealResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DealResponse) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

type DealsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deals         []*DealResponse        `protobuf:"bytes,1,rep,name=deals,proto3" json:"deals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DealsList) Reset() {
	*x = DealsList{}
	mi := &file_proto_deals_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DealsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealsList) ProtoMessage() {}

func (x *DealsList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deals_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealsList.ProtoReflect.Descriptor instead.
func (*DealsList) Descriptor() ([]byte, []int) {
	return file_proto_deals_proto_rawDescGZIP(), []int{3}
}

func (x *DealsList) GetDeals() []*DealResponse {
	if x != nil {
		return x.Deals
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_deals_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deals_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_deals_proto_rawDescGZIP(), []int{4}
}

var File_proto_deals_proto protoreflect.FileDescriptor

const file_proto_deals_proto_rawDesc = "" +
	"\n" +
	"\x11proto/deals.proto\x12\x05deals\"v\n" +
	"\x11CreateDealRequest\x12\x1d\n" +
	"\n" +
	"contact_id\x18\x01 \x01(\tR\tcontactId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x14\n" +
	"\x05stage\x18\x04 \x01(\tR\x05stage\" \n" +
	"\x0eGetDealRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x81\x01\n" +
	"\fDealResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"contact_id\x18\x02 \x01(\tR\tcontactId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x14\n" +
	"\x05stage\x18\x05 \x01(\tR\x05stage\"6\n" +
	"\tDealsList\x12)\n" +
	"\x05deals\x18\x01 \x03(\v2\x13.deals.DealResponseR\x05deals\"\a\n" +
	"\x05Empty2\xaf\x01\n" +
	"\fDealsService\x12;\n" +
	"\n" +
	"CreateDeal\x12\x18.deals.CreateDealRequest\x1a\x13.deals.DealResponse\x125\n" +
	"\aGetDeal\x12\x15.deals.GetDealRequest\x1a\x13.deals.DealResponse\x12+\n" +
	"\tListDeals\x12\f.deals.Empty\x1a\x10.deals.DealsListB\x13Z\x11proto/deals;dealsb\x06proto3"

var (
	file_proto_deals_proto_rawDescOnce sync.Once
	file_proto_deals_proto_rawDescData []byte
)

func file_proto_deals_proto_rawDescGZIP() []byte {
	file_proto_deals_proto_rawDescOnce.Do(func() {
		file_proto_deals_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_deals_proto_rawDesc), len(file_proto_deals_proto_rawDesc)))
	})
	return file_proto_deals_proto_rawDescData
}

var file_proto_deals_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_deals_proto_goTypes = []any{
	(*CreateDealRequest)(nil), // 0: deals.CreateDealRequest
	(*GetDealRequest)(nil),    // 1: deals.GetDealRequest
	(*DealResponse)(nil),      // 2: deals.DealResponse
	(*DealsList)(nil),         // 3: deals.DealsList
	(*Empty)(nil),             // 4: deals.Empty
}
var file_proto_deals_proto_depIdxs = []int32{
	2, // 0: deals.DealsList.deals:type_name -> deals.DealResponse
	0, // 1: deals.DealsService.CreateDeal:input_type -> deals.CreateDealRequest
	1, // 2: deals.DealsService.GetDeal:input_type -> deals.GetDealRequest
	4, // 3: deals.DealsService.ListDeals:input_type -> deals.Empty
	2, // 4: deals.DealsService.CreateDeal:output_type -> deals.DealResponse
	2, // 5: deals.DealsService.GetDeal:output_type -> deals.DealResponse
	3, // 6: deals.DealsService.ListDeals:output_type -> deals.DealsList
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_deals_proto_init() }
func file_proto_deals_proto_init() {
	if File_proto_deals_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_deals_proto_rawDesc), len(file_proto_deals_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_deals_proto_goTypes,
		DependencyIndexes: file_proto_deals_proto_depIdxs,
		MessageInfos:      file_proto_deals_proto_msgTypes,
	}.Build()
	File_proto_deals_proto = out.File
	file_proto_deals_proto_goTypes = nil
	file_proto_deals_proto_depIdxs = nil
}
