// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/deals.proto

package deals

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DealsService_CreateDeal_FullMethodName = "/deals.DealsService/CreateDeal"
	DealsService_GetDeal_FullMethodName    = "/deals.DealsService/GetDeal"
	DealsService_ListDeals_FullMethodName  = "/deals.DealsService/ListDeals"
)

// DealsServiceClient is the client API for DealsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DealsServiceClient interface {
	CreateDeal(ctx context.Context, in *CreateDealRequest, opts ...grpc.CallOption) (*DealResponse, error)
	GetDeal(ctx context.Context, in *GetDealRequest, opts ...grpc.CallOption) (*DealResponse, error)
	ListDeals(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DealsList, error)
}

type dealsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDealsServiceClient(cc grpc.ClientConnInterface) DealsServiceClient {
	return &dealsServiceClient{cc}
}

func (c *dealsServiceClient) CreateDeal(ctx context.Context, in *CreateDealRequest, opts ...grpc.CallOption) (*DealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DealResponse)
	err := c.cc.Invoke(ctx, DealsService_CreateDeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dealsServiceClient) GetDeal(ctx context.Context, in *GetDealRequest, opts ...grpc.CallOption) (*DealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DealResponse)
	err := c.cc.Invoke(ctx, DealsService_GetDeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dealsServiceClient) ListDeals(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DealsList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DealsList)
	err := c.cc.Invoke(ctx, DealsService_ListDeals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DealsServiceServer is the server API for DealsService service.
// All implementations must embed UnimplementedDealsServiceServer
// for forward compatibility.
type DealsServiceServer interface {
	CreateDeal(context.Context, *CreateDealRequest) (*DealResponse, error)
	GetDeal(context.Context, *GetDealRequest) (*DealResponse, error)
	ListDeals(context.Context, *Empty) (*DealsList, error)
	mustEmbedUnimplementedDealsServiceServer()
}

// UnimplementedDealsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDealsServiceServer struct{}

func (UnimplementedDealsServiceServer) CreateDeal(context.Context, *CreateDealRequest) (*DealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDeal not implemented")
}
func (UnimplementedDealsServiceServer) GetDeal(context.Context, *GetDealRequest) (*DealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeal not implemented")
}
func (UnimplementedDealsServiceServer) ListDeals(context.Context, *Empty) (*DealsList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDeals not implemented")
}
func (UnimplementedDealsServiceServer) mustEmbedUnimplementedDealsServiceServer() {}
func (UnimplementedDealsServiceServer) testEmbeddedByValue()                      {}

// UnsafeDealsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DealsServiceServer will
// result in compilation errors.
type UnsafeDealsServiceServer interface {
	mustEmbedUnimplementedDealsServiceServer()
}

func RegisterDealsServiceServer(s grpc.ServiceRegistrar, srv DealsServiceServer) {
	// If the following call pancis, it indicates UnimplementedDealsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DealsService_ServiceDesc, srv)
}

func _DealsService_CreateDeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DealsServiceServer).CreateDeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DealsService_CreateDeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DealsServiceServer).CreateDeal(ctx, req.(*CreateDealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DealsService_GetDeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DealsServiceServer).GetDeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DealsService_GetDeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DealsServiceServer).GetDeal(ctx, req.(*GetDealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DealsService_ListDeals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DealsServiceServer).ListDeals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DealsService_ListDeals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DealsServiceServer).ListDeals(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DealsService_ServiceDesc is the grpc.ServiceDesc for DealsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DealsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deals.DealsService",
	HandlerType: (*DealsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDeal",
			Handler:    _DealsService_CreateDeal_Handler,
		},
		{
			MethodName: "GetDeal",
			Handler:    _DealsService_GetDeal_Handler,
		},
		{
			MethodName: "ListDeals",
			Handler:    _DealsService_ListDeals_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/deals.proto",
}
