// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/gateway.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Contactos
type ContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactRequest) Reset() {
	*x = ContactRequest{}
	mi := &file_proto_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactRequest) ProtoMessage() {}

func (x *ContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactRequest.ProtoReflect.Descriptor instead.
func (*ContactRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *ContactRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContactRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ContactRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type ContactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactResponse) Reset() {
	*x = ContactResponse{}
	mi := &file_proto_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactResponse) ProtoMessage() {}

func (x *ContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactResponse.ProtoReflect.Descriptor instead.
func (*ContactResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *ContactResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContactResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContactResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ContactResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type ContactId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactId) Reset() {
	*x = ContactId{}
	mi := &file_proto_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactId) ProtoMessage() {}

func (x *ContactId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactId.ProtoReflect.Descriptor instead.
func (*ContactId) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *ContactId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Deals
type DealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContactId     string                 `protobuf:"bytes,1,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Stage         string                 `protobuf:"bytes,4,opt,name=stage,proto3" json:"stage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DealRequest) Reset() {
	*x = DealRequest{}
	mi := &file_proto_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealRequest) ProtoMessage() {}

func (x *DealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealRequest.ProtoReflect.Descriptor instead.
func (*DealRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *DealRequest) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

func (x *DealRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DealRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DealRequest) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

type DealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContactId     string                 `protobuf:"bytes,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Stage         string                 `protobuf:"bytes,5,opt,name=stage,proto3" json:"stage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DealResponse) Reset() {
	*x = DealResponse{}
	mi := &file_proto_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealResponse) ProtoMessage() {}

func (x *DealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealResponse.ProtoReflect.Descriptor instead.
func (*DealResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *DealResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DealResponse) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

func (x *DealResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DealResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DealResponse) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

type DealId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DealId) Reset() {
	*x = DealId{}
	mi := &file_proto_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DealId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealId) ProtoMessage() {}

func (x *DealId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealId.ProtoReflect.Descriptor instead.
func (*DealId) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *DealId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_gateway_proto protoreflect.FileDescriptor

const file_proto_gateway_proto_rawDesc = "" +
	"\n" +
	"\x13proto/gateway.proto\x12\agateway\"P\n" +
	"\x0eContactRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\"a\n" +
	"\x0fContactResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\"\x1b\n" +
	"\tContactId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"p\n" +
	"\vDealRequest\x12\x1d\n" +
	"\n" +
	"contact_id\x18\x01 \x01(\tR\tcontactId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x14\n" +
	"\x05stage\x18\x04 \x01(\tR\x05stage\"\x81\x01\n" +
	"\fDealResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"contact_id\x18\x02 \x01(\tR\tcontactId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x14\n" +
	"\x05stage\x18\x05 \x01(\tR\x05stage\"\x18\n" +
	"\x06DealId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xfe\x01\n" +
	"\x0eGatewayService\x12B\n" +
	"\rCreateContact\x12\x17.gateway.ContactRequest\x1a\x18.gateway.ContactResponse\x12:\n" +
	"\n" +
	"GetContact\x12\x12.gateway.ContactId\x1a\x18.gateway.ContactResponse\x129\n" +
	"\n" +
	"CreateDeal\x12\x14.gateway.DealRequest\x1a\x15.gateway.DealResponse\x121\n" +
	"\aGetDeal\x12\x0f.gateway.DealId\x1a\x15.gateway.DealResponseB\x17Z\x15proto/gateway;gatewayb\x06proto3"

var (
	file_proto_gateway_proto_rawDescOnce sync.Once
	file_proto_gateway_proto_rawDescData []byte
)

func file_proto_gateway_proto_rawDescGZIP() []byte {
	file_proto_gateway_proto_rawDescOnce.Do(func() {
		file_proto_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gateway_proto_rawDesc), len(file_proto_gateway_proto_rawDesc)))
	})
	return file_proto_gateway_proto_rawDescData
}

var file_proto_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_gateway_proto_goTypes = []any{
	(*ContactRequest)(nil),  // 0: gateway.ContactRequest
	(*ContactResponse)(nil), // 1: gateway.ContactResponse
	(*ContactId)(nil),       // 2: gateway.ContactId
	(*DealRequest)(nil),     // 3: gateway.DealRequest
	(*DealResponse)(nil),    // 4: gateway.DealResponse
	(*DealId)(nil),          // 5: gateway.DealId
}
var file_proto_gateway_proto_depIdxs = []int32{
	0, // 0: gateway.GatewayService.CreateContact:input_type -> gateway.ContactRequest
	2, // 1: gateway.GatewayService.GetContact:input_type -> gateway.ContactId
	3, // 2: gateway.GatewayService.CreateDeal:input_type -> gateway.DealRequest
	5, // 3: gateway.GatewayService.GetDeal:input_type -> gateway.DealId
	1, // 4: gateway.GatewayService.CreateContact:output_type -> gateway.ContactResponse
	1, // 5: gateway.GatewayService.GetContact:output_type -> gateway.ContactResponse
	4, // 6: gateway.GatewayService.CreateDeal:output_type -> gateway.DealResponse
	4, // 7: gateway.GatewayService.GetDeal:output_type -> gateway.DealResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_gateway_proto_init() }
func file_proto_gateway_proto_init() {
	if File_proto_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gateway_proto_rawDesc), len(file_proto_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gateway_proto_goTypes,
		DependencyIndexes: file_proto_gateway_proto_depIdxs,
		MessageInfos:      file_proto_gateway_proto_msgTypes,
	}.Build()
	File_proto_gateway_proto = out.File
	file_proto_gateway_proto_goTypes = nil
	file_proto_gateway_proto_depIdxs = nil
}
