apiVersion: apps/v1
kind: Deployment
metadata:
  name: deals-deployment
  namespace: crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deals
  template:
    metadata:
      labels:
        app: deals
    spec:
      containers:
        - name: deals
          image: armando/deals:latest    # <-- reemplaza si tu imagen es distinta
          imagePullPolicy: Never 
          ports:
            - containerPort: 50052
          env:
            - name: DB_HOST
              value: "crm-db"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "crmuser"
            - name: DB_PASS
              value: "crmpassword"
            - name: CONTACTS_GRPC_ADDRESS
              value: "contacts-service.crm.svc.cluster.local:50052"
          readinessProbe:
            tcpSocket:
              port: 50052
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 50052
            initialDelaySeconds: 5
            periodSeconds: 10
