apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: crm
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80          # Puerto expuesto hacia afuera del cluster
      targetPort: 8080  # Puerto interno del gateway
