apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: crm-db
  namespace: crm
spec:
  selector:
    matchLabels:
      app: crm-db
  serviceName: "crm-db"
  replicas: 1
  template:
    metadata:
      labels:
        app: crm-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: crm-db-secret
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: db-storage
        namespace: crm
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
