// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/contacts.proto

package contacts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mensajes de solicitud y respuesta
type CreateContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContactRequest) Reset() {
	*x = CreateContactRequest{}
	mi := &file_proto_contacts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContactRequest) ProtoMessage() {}

func (x *CreateContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contacts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContactRequest.ProtoReflect.Descriptor instead.
func (*CreateContactRequest) Descriptor() ([]byte, []int) {
	return file_proto_contacts_proto_rawDescGZIP(), []int{0}
}

func (x *CreateContactRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateContactRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateContactRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type GetContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContactRequest) Reset() {
	*x = GetContactRequest{}
	mi := &file_proto_contacts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactRequest) ProtoMessage() {}

func (x *GetContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contacts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactRequest.ProtoReflect.Descriptor instead.
func (*GetContactRequest) Descriptor() ([]byte, []int) {
	return file_proto_contacts_proto_rawDescGZIP(), []int{1}
}

func (x *GetContactRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContactRequest) Reset() {
	*x = DeleteContactRequest{}
	mi := &file_proto_contacts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContactRequest) ProtoMessage() {}

func (x *DeleteContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contacts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContactRequest.ProtoReflect.Descriptor instead.
func (*DeleteContactRequest) Descriptor() ([]byte, []int) {
	return file_proto_contacts_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteContactRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ContactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactResponse) Reset() {
	*x = ContactResponse{}
	mi := &file_proto_contacts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactResponse) ProtoMessage() {}

func (x *ContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contacts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactResponse.ProtoReflect.Descriptor instead.
func (*ContactResponse) Descriptor() ([]byte, []int) {
	return file_proto_contacts_proto_rawDescGZIP(), []int{3}
}

func (x *ContactResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContactResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContactResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ContactResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type ContactsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contacts      []*ContactResponse     `protobuf:"bytes,1,rep,name=contacts,proto3" json:"contacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactsList) Reset() {
	*x = ContactsList{}
	mi := &file_proto_contacts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactsList) ProtoMessage() {}

func (x *ContactsList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contacts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactsList.ProtoReflect.Descriptor instead.
func (*ContactsList) Descriptor() ([]byte, []int) {
	return file_proto_contacts_proto_rawDescGZIP(), []int{4}
}

func (x *ContactsList) GetContacts() []*ContactResponse {
	if x != nil {
		return x.Contacts
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_contacts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contacts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_contacts_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_contacts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contacts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_contacts_proto_rawDescGZIP(), []int{6}
}

var File_proto_contacts_proto protoreflect.FileDescriptor

const file_proto_contacts_proto_rawDesc = "" +
	"\n" +
	"\x14proto/contacts.proto\x12\bcontacts\"V\n" +
	"\x14CreateContactRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\"#\n" +
	"\x11GetContactRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"&\n" +
	"\x14DeleteContactRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"a\n" +
	"\x0fContactResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\"E\n" +
	"\fContactsList\x125\n" +
	"\bcontacts\x18\x01 \x03(\v2\x19.contacts.ContactResponseR\bcontacts\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\a\n" +
	"\x05Empty2\xa7\x02\n" +
	"\x0fContactsService\x12J\n" +
	"\rCreateContact\x12\x1e.contacts.CreateContactRequest\x1a\x19.contacts.ContactResponse\x12D\n" +
	"\n" +
	"GetContact\x12\x1b.contacts.GetContactRequest\x1a\x19.contacts.ContactResponse\x127\n" +
	"\fListContacts\x12\x0f.contacts.Empty\x1a\x16.contacts.ContactsList\x12I\n" +
	"\rDeleteContact\x12\x1e.contacts.DeleteContactRequest\x1a\x18.contacts.DeleteResponseB\x19Z\x17proto/contacts;contactsb\x06proto3"

var (
	file_proto_contacts_proto_rawDescOnce sync.Once
	file_proto_contacts_proto_rawDescData []byte
)

func file_proto_contacts_proto_rawDescGZIP() []byte {
	file_proto_contacts_proto_rawDescOnce.Do(func() {
		file_proto_contacts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_contacts_proto_rawDesc), len(file_proto_contacts_proto_rawDesc)))
	})
	return file_proto_contacts_proto_rawDescData
}

var file_proto_contacts_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_contacts_proto_goTypes = []any{
	(*CreateContactRequest)(nil), // 0: contacts.CreateContactRequest
	(*GetContactRequest)(nil),    // 1: contacts.GetContactRequest
	(*DeleteContactRequest)(nil), // 2: contacts.DeleteContactRequest
	(*ContactResponse)(nil),      // 3: contacts.ContactResponse
	(*ContactsList)(nil),         // 4: contacts.ContactsList
	(*DeleteResponse)(nil),       // 5: contacts.DeleteResponse
	(*Empty)(nil),                // 6: contacts.Empty
}
var file_proto_contacts_proto_depIdxs = []int32{
	3, // 0: contacts.ContactsList.contacts:type_name -> contacts.ContactResponse
	0, // 1: contacts.ContactsService.CreateContact:input_type -> contacts.CreateContactRequest
	1, // 2: contacts.ContactsService.GetContact:input_type -> contacts.GetContactRequest
	6, // 3: contacts.ContactsService.ListContacts:input_type -> contacts.Empty
	2, // 4: contacts.ContactsService.DeleteContact:input_type -> contacts.DeleteContactRequest
	3, // 5: contacts.ContactsService.CreateContact:output_type -> contacts.ContactResponse
	3, // 6: contacts.ContactsService.GetContact:output_type -> contacts.ContactResponse
	4, // 7: contacts.ContactsService.ListContacts:output_type -> contacts.ContactsList
	5, // 8: contacts.ContactsService.DeleteContact:output_type -> contacts.DeleteResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_contacts_proto_init() }
func file_proto_contacts_proto_init() {
	if File_proto_contacts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_contacts_proto_rawDesc), len(file_proto_contacts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_contacts_proto_goTypes,
		DependencyIndexes: file_proto_contacts_proto_depIdxs,
		MessageInfos:      file_proto_contacts_proto_msgTypes,
	}.Build()
	File_proto_contacts_proto = out.File
	file_proto_contacts_proto_goTypes = nil
	file_proto_contacts_proto_depIdxs = nil
}
